version: '3.2'
services:
  # age_classificator:
  #   image: python:3.10-alpine3.20
  #   volumes:
  #     - ./backend/age_classificator:/app
  #   command: > 
  #     /bin/sh -c "apk add --no-cache make && 
  #     pip install -r /app/requirements.txt && 
  #     cd /app && make"
  # FIXME: Not Working
  # face_detector:
  #   image: python:3.10-slim
  #   volumes:
  #     - ./backend/face_detector:/app
  #   command: >
  #     /bin/sh -c "apk add --no-cache build-base libffi-dev openblas-dev gfortran py3-pip &&
  #     pip install --no-cache-dir numpy &&
  #     pip install --no-cache-dir opencv-python-headless &&
  #     cd /app && make"

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
